#!/bin/bash

# Retrieve arguments
domain=$(sudo yunohost app setting browsepass domain)
path=$(sudo yunohost app setting browsepass path)
user=$(sudo yunohost app setting browsepass ftp_user)
is_public=$(sudo yunohost app setting browsepass is_public)
final_path=/var/www/browsepass

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@YNH_WWW_PATH@$path@g" ../conf/nginx.conf
sed -i "s@YNH_WWW_ALIAS@$final_path/@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/browsepass.conf

# Make app public if necessary
if [ "$is_public" = "Yes" ];
then
    sudo yunohost app setting browsepass skipped_uris -v "/"
fi

# Reload Nginx and regenerate SSOwat conf
sudo service nginx reload
sudo yunohost app ssowatconf
